name: CI

on: 
      push:
            branches: 
                  - main
                  - develop

      pull_request:
            branches: 
                  - main
jobs:
     
      backend: 
            name: Backend CI
            runs-on: ubuntu-latest
            
            defaults:
                  run:
                        working-directory: backend
            steps:
                  - name: Checkout
                    uses: actions/checkout@v4

                  - name: Set up Node.js
                    uses: actions/setup-node@v4
                    with:
                        node-version: 22
                        cache: 'npm'
                        cache-dependency-path: backend/package-lock.json

                  - name: Install dependencies
                    run: npm install

                  - name: Check application
                    run: node --check src/server.js
      
      frontend:
            name: Frontend CI
            runs-on: ubuntu-latest
            defaults:
                  run:
                        working-directory: frontend
            steps:
                  - name: Checkout
                    uses: actions/checkout@v4

                  - name: Set up Node
                    uses: actions/setup-node@v4
                    with:
                        node-version: 22
                        cache: 'npm'
                        cache-dependency-path: frontend/package-lock.json

                  - name: Install dependencies
                    run: npm install

                  - name: Check application
                    run: npm run build